package me.oikvpqya.apps.music.ui.util

import androidx.compose.ui.unit.dp

val LIST_TRACK_ALBUM_SMALL_SIZE = 24.dp
val LIST_TRACK_ALBUM_NORMAL_SIZE = 40.dp
val LIST_TRACK_ALBUM_LARGE_SIZE = 56.dp
val LIST_TRACK_ALBUM_LARGE_SMALL_SIZE = 88.dp
val LIST_TRACK_ALBUM_LARGE_NORMAL_SIZE = 120.dp
val LIST_TRACK_ALBUM_LARGE_LARGE_SIZE = 152.dp
val LIST_TRACK_ALBUM_SIZE = LIST_TRACK_ALBUM_LARGE_SIZE
val LIST_TRACK_CONTAINER_HEIGHT = LIST_TRACK_ALBUM_SIZE + 16.dp
val APP_BAR_CONTAINER_HEIGHT = 64.dp
val BOTTOM_BAR_CONTAINER_HEIGHT = 80.dp

object AppUiConstant {

}
